name: Destroy Azure AKS With Terraform
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  AKS-Cluster-Destroy:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.1.7"
        
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: azure login
        run: az login

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      
      - name: Terraform Output
        run: terraform output

      #- name: Deploy Application
      #  run: |
      #    az aks get-credentials -n "cluster-bursting-jennet" -g "rg-refined-swine"
      #    kubectl apply -f ./AKSApp/aks-store-quickstart.yaml
      #    sleep 40
      #    kubectl get service store-front
      #    rm -rf ~/.kube